### ISSUE TITLE
What was the final report？

### ISSUE THREAD

**Issue by qwteyyriywy** [0shelter0/CSTTN#1]
Hello, thanks for sharing your work about CSTTN! Recently, I run your original code using default configs but I do not sure the final result. I want to ask the final training results or are there any papers related to this model? If so,can you share it so that I can learn from it.
Looking for your reply, thanks sincerely.
Regard!

**Comment by 0shelter0** [comment]
Well, thanks for your attention to our work, we have added the original paper corresponding to the code, please check out the `pdf` file at [CSTTN_FINAL.pdf](https://github.com/0shelter0/CSTTN/blob/main/figures/CSTTN_FINAL.pdf).

**Comment by vullis0** [comment]
Hello, I would like to ask how the ablation experiment in this experiment was completed in the report you sent above
Looking for your reply, thanks sincerely.
Regard!
